name: API Security Maturity Gate

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  validate-security-maturity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq (Go version)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Calculate security maturity score
        id: calculate_score
        run: |
          # Use yq to sum all the '1's in the YAML file
          TOTAL_SCORE=$(yq e '.. | select(tag == "!!int" and . == 1)' contracts/df/tr-test-petstore-java/.api-security.yaml | wc -l)
          echo "🔒 API Security Maturity Score: $TOTAL_SCORE"
          echo "score=$TOTAL_SCORE" >> $GITHUB_OUTPUT

      - name: Check against minimum threshold
        run: |
          MINIMUM_SCORE=15  # Adjust this threshold as needed
          if [ "${{ steps.calculate_score.outputs.score }}" -lt "$MINIMUM_SCORE" ]; then
            echo "API security maturity score is below the minimum threshold of $MINIMUM_SCORE."
            echo "Please update your .api-security.yaml to increase the score before merging."
            exit 1
          else
            echo "API security maturity score meets the minimum threshold."
          fi